//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woben.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woben.Web.Resources.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu cuenta ha sido bloqueada por {0} más  {1}.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu cuenta ha sido bloqueada durante {0} minutos.
        /// </summary>
        public static string AccountLockedForMinutes {
            get {
                return ResourceManager.GetString("AccountLockedForMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este login externo ya está asociado a otra cuenta en Woben.
        /// </summary>
        public static string ExternalLoginAlreadyLinked {
            get {
                return ResourceManager.GetString("ExternalLoginAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar loguearse con el proveedor externo.
        /// </summary>
        public static string ExternalLoginError {
            get {
                return ResourceManager.GetString("ExternalLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes que proporcionar tu usuario y código de confirmación.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El password no es correcto. Intentos restantes = {0}.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún usuario registrado en Woben con el nombre indicado.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string MailerAbout {
            get {
                return ResourceManager.GetString("MailerAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://woben-web-dev.azurewebsites.net/about.
        /// </summary>
        public static string MailerAboutUrl {
            get {
                return ResourceManager.GetString("MailerAboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string MailerContact {
            get {
                return ResourceManager.GetString("MailerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://woben-web-dev.azurewebsites.net/contact.
        /// </summary>
        public static string MailerContactUrl {
            get {
                return ResourceManager.GetString("MailerContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MailerHome {
            get {
                return ResourceManager.GetString("MailerHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://woben-web-dev.azurewebsites.net.
        /// </summary>
        public static string MailerHomeUrl {
            get {
                return ResourceManager.GetString("MailerHomeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario {0} te ha enviado un nuevo mensaje.
        /// </summary>
        public static string MailerMessageDescription {
            get {
                return ResourceManager.GetString("MailerMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a mensajes.
        /// </summary>
        public static string MailerMessageGoTo {
            get {
                return ResourceManager.GetString("MailerMessageGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has recibido el siguiente mensaje.
        /// </summary>
        public static string MailerMessageMessageReceived {
            get {
                return ResourceManager.GetString("MailerMessageMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has recibido un nuevo mensaje.
        /// </summary>
        public static string MailerMessageTitle {
            get {
                return ResourceManager.GetString("MailerMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://woben-web-dev.azurewebsites.net/dashboard/mesages.
        /// </summary>
        public static string MailerMessageUrl {
            get {
                return ResourceManager.GetString("MailerMessageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woben, ventajas para empleados.
        /// </summary>
        public static string MailerTitle {
            get {
                return ResourceManager.GetString("MailerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el usuario.
        /// </summary>
        public static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segundos.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe o bien no está confirmado.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de nueva cuenta en Woben.
        /// </summary>
        public static string WobenAccountConfimation {
            get {
                return ResourceManager.GetString("WobenAccountConfimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de cuenta en Woben.
        /// </summary>
        public static string WobenAccountConfirmation {
            get {
                return ResourceManager.GetString("WobenAccountConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reseteo de password en Woben.
        /// </summary>
        public static string WobenResetPassword {
            get {
                return ResourceManager.GetString("WobenResetPassword", resourceCulture);
            }
        }
    }
}
