//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woben.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woben.Web.Resources.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu cuenta ha sido bloqueada por {0} más  {1}.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu cuenta ha sido bloqueada durante {0} minutos.
        /// </summary>
        public static string AccountLockedForMinutes {
            get {
                return ResourceManager.GetString("AccountLockedForMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este login externo ya está asociado a otra cuenta en Woben.
        /// </summary>
        public static string ExternalLoginAlreadyLinked {
            get {
                return ResourceManager.GetString("ExternalLoginAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar loguearse con el proveedor externo.
        /// </summary>
        public static string ExternalLoginError {
            get {
                return ResourceManager.GetString("ExternalLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes que proporcionar tu usuario y código de confirmación.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El password no es correcto. Intentos restantes = {0}.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ningún usuario registrado en Woben con el nombre indicado.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string MailerAbout {
            get {
                return ResourceManager.GetString("MailerAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://woben-web-dev.azurewebsites.net/about.
        /// </summary>
        public static string MailerAboutUrl {
            get {
                return ResourceManager.GetString("MailerAboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string MailerContact {
            get {
                return ResourceManager.GetString("MailerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://woben-web-dev.azurewebsites.net/contact.
        /// </summary>
        public static string MailerContactUrl {
            get {
                return ResourceManager.GetString("MailerContactUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://woben-web-dev.azurewebsites.net/dashboard.
        /// </summary>
        public static string MailerDashboardUrl {
            get {
                return ResourceManager.GetString("MailerDashboardUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://facebook.com.
        /// </summary>
        public static string MailerFacebookUrl {
            get {
                return ResourceManager.GetString("MailerFacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a mensajes.
        /// </summary>
        public static string MailerGoToMessages {
            get {
                return ResourceManager.GetString("MailerGoToMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a las notificaciones.
        /// </summary>
        public static string MailerGoToNotifications {
            get {
                return ResourceManager.GetString("MailerGoToNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string MailerHome {
            get {
                return ResourceManager.GetString("MailerHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://woben-web-dev.azurewebsites.net.
        /// </summary>
        public static string MailerHomeUrl {
            get {
                return ResourceManager.GetString("MailerHomeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La hora de llamada es indiferente.
        /// </summary>
        public static string MailerIndiferent {
            get {
                return ResourceManager.GetString("MailerIndiferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llamar por las tardes.
        /// </summary>
        public static string MailerIntheAfternoon {
            get {
                return ResourceManager.GetString("MailerIntheAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llamar por las mañanas.
        /// </summary>
        public static string MailerIntheMornings {
            get {
                return ResourceManager.GetString("MailerIntheMornings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has recibido un nuevo mensaje.
        /// </summary>
        public static string MailerMessageDescription {
            get {
                return ResourceManager.GetString("MailerMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la consola de administración.
        /// </summary>
        public static string MailerMessageGoTo {
            get {
                return ResourceManager.GetString("MailerMessageGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario @{0} ha escrito lo siguiente.
        /// </summary>
        public static string MailerMessageMessageReceived {
            get {
                return ResourceManager.GetString("MailerMessageMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola administrador.
        /// </summary>
        public static string MailerMessageTitle {
            get {
                return ResourceManager.GetString("MailerMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://woben-web-dev.azurewebsites.net/dashboard/messages.
        /// </summary>
        public static string MailerMessageUrl {
            get {
                return ResourceManager.GetString("MailerMessageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola @{0}, el último paso para registrarse en Woben es que verifiques tu direccion de mail. Pulsa el siguiente botón para finalizar.
        /// </summary>
        public static string MailerNewAccountDescription {
            get {
                return ResourceManager.GetString("MailerNewAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma tu cuenta.
        /// </summary>
        public static string MailerNewAccountLink {
            get {
                return ResourceManager.GetString("MailerNewAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A punto de finalizar ....
        /// </summary>
        public static string MailerNewAccountTitle {
            get {
                return ResourceManager.GetString("MailerNewAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has recibido una nueva notificación acerca de un producto.
        /// </summary>
        public static string MailerNotificationDescription {
            get {
                return ResourceManager.GetString("MailerNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://woben-web-dev.azurewebsites.net/dashboard/notifications.
        /// </summary>
        public static string MailerNotificationUrl {
            get {
                return ResourceManager.GetString("MailerNotificationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola @{0}, pulsando en el siguiente botón te llevaremos a la página donde podrás modificar tu password.
        /// </summary>
        public static string MailerPasswordResetDescription {
            get {
                return ResourceManager.GetString("MailerPasswordResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica tu password.
        /// </summary>
        public static string MailerPasswordResetLink {
            get {
                return ResourceManager.GetString("MailerPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A punto de modificar tu password ....
        /// </summary>
        public static string MailerPasswordResetTitle {
            get {
                return ResourceManager.GetString("MailerPasswordResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra dirección de mail es admin@woben.com.
        /// </summary>
        public static string MailerReasonAddress {
            get {
                return ResourceManager.GetString("MailerReasonAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estas recibiendo este mail poque has creado una cuenta en Woben.
        /// </summary>
        public static string MailerReasonDescription {
            get {
                return ResourceManager.GetString("MailerReasonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Woben, ventajas para empleados.
        /// </summary>
        public static string MailerTitle {
            get {
                return ResourceManager.GetString("MailerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://twitter.com.
        /// </summary>
        public static string MailerTwitterUrl {
            get {
                return ResourceManager.GetString("MailerTwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minute(s).
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Woben] Se ha recibido un nuevo mensaje.
        /// </summary>
        public static string NewMessageReceived {
            get {
                return ResourceManager.GetString("NewMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Woben] Se ha recibido una nueva notificación acerca del producto {0}.
        /// </summary>
        public static string NewNotificationReceived {
            get {
                return ResourceManager.GetString("NewNotificationReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el usuario.
        /// </summary>
        public static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a segundos.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no existe o bien no está confirmado.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Woben] Confirmación de nueva cuenta.
        /// </summary>
        public static string WobenAccountConfirmation {
            get {
                return ResourceManager.GetString("WobenAccountConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Woben] Modificación de password.
        /// </summary>
        public static string WobenResetPassword {
            get {
                return ResourceManager.GetString("WobenResetPassword", resourceCulture);
            }
        }
    }
}
